# HOST_IP is the the ip of your device on the current network
# It is required to have connection from the service to the broker
# and from the ui to the broker

services:
  kafka:
    image: lensesio/fast-data-dev
    ports:
      - "9092:9092"
      - "3030:3030"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLED: false
      ADV_HOST: ${HOST_IP}
      ADV_PORT: 9092
      SAMPLE_DATA: 0
    networks:
      - default

  kafbat-ui:
    image: ghcr.io/kafbat/kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${HOST_IP}:9092
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: LocalCluster
    networks:
      - default

networks:
  default:
    driver: bridge